--- #YAML:1.0
name:               Text-Haml
version:            0.990104
abstract:           Haml parser
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Encode:        0
    IO::File:      0
    perl:          5.008007
    Scalar::Util:  0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/vti/text-haml
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
