---
abstract: 'Haml Perl implementation'
author:
  - 'Viacheslav Tykhanovskyi, C<vti@cpan.org>.'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Haml
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Text::Haml:
    file: lib/Text/Haml.pm
    version: 0.990116
requires:
  Carp: 0
  Data::Section::Simple: 0
  Encode: 0
  File::Basename: 0
  File::Spec: 0
  IO::File: 0
  Scalar::Util: 0
  URI::Escape: 0
resources:
  bugtracker: https://github.com/vti/text-haml/issues
  homepage: https://github.com/vti/text-haml
  repository: git://github.com/vti/text-haml.git
version: 0.990116
x_contributors:
  - 'enosis <enosis@github.com>'
  - 'rightgo09 <skyarrow09@gmail.com>'
  - 'Breno G. de Oliveira <garu@cpan.org>'
  - 'Yuya Tanaka <yuya.presto@gmail.com>'
  - 'Carlos Lima <carlos@carlos>'
  - 'Jason Younker <jason@ynkr.org>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Evgenni Grishkovelli <grishkovelli@gmail.com>'
  - 'Hyungsuk Hong <aanoaa@gmail.com>'
  - 'Keedi Kim <keedi.k@gmail.com>'
  - 'TheAthlete <theathlet@yandex.ru>'
  - 'vti <viacheslav.t@gmail.com>'
